name: Deploy Next.js Frontend to AWS EC2

on:
  push:
    branches:
      - nextjs-migration-autodeploy  # Adjust this to the branch you use for frontend updates

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync repository and Build Frontend
      run: |
        ssh -o "StrictHostKeyChecking=no" ubuntu@34.228.40.50 <<'EOF'
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          nvm use 20.12.1 || exit 1
          cd ~/csc648-848-05-sw-engineering-sp24-05/
          git pull origin nextjs-migration-autodeploy
          cd application/client/
          npm install
          npm run build
          pm2 reload next-app  # Replace `next-app` with the pm2 name for your Next.js app
        EOF

    - name: Update Nginx Configuration
      run: |
        ssh ubuntu@34.228.40.50 <<EOF
          sudo nginx -t && sudo systemctl reload nginx
        EOF