name: Deploy ExpressJS Backend to AWS EC2

on:
  push:
    branches:
      - implementAPI  # This workflow triggers on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The type of runner that the job will run on
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync repository and Build
      run: |
        ssh -o "StrictHostKeyChecking=no" ubuntu@54.163.16.75 <<EOF
          export NVM_DIR="$HOME/.nvm"
          [ -s "\$NVM_DIR/nvm.sh" ] && \. "\$NVM_DIR/nvm.sh"  # This loads nvm
          [ -s "\$NVM_DIR/bash_completion" ] && \. "\$NVM_DIR/bash_completion"  # This loads nvm bash_completion (optional)
          cd ~/csc648-848-05-sw-engineering-sp24-05/
          git pull origin implementAPI
          cd application/backend/
          /home/ubuntu/.nvm/versions/node/v20.12.1/bin/npm install
          /home/ubuntu/.nvm/versions/node/v20.12.1/bin/npm run build
        EOF

    - name: Reload server
      run: |
        ssh ubuntu@54.163.16.75 <<EOF
          cd ~/csc648-848-05-sw-engineering-sp24-05/application/backend/
          pm2 reload ecosystem.config.json --update-env
        EOF