name: Deploy ExpressJS Backend to AWS EC2

on:
  push:
    branches:
      - implementAPI  # This workflow triggers on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The type of runner that the job will run on
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync repository and Build
      run: |
        ssh -o "StrictHostKeyChecking=no" ubuntu@54.163.16.75 <<EOF
          source ~/.bashrc  # Source the bashrc to ensure NVM is initialized
          nvm use 20.12.1
          if [ $? -ne 0 ]; then
            echo "Failed to switch to Node.js 20.12.1"
            exit 1
          fi
          cd ~/csc648-848-05-sw-engineering-sp24-05/
          git pull origin implementAPI
          cd application/backend/
          npm install
          npm run build
        EOF

    - name: Reload server
      run: |
        ssh ubuntu@54.163.16.75 <<EOF
          cd ~/csc648-848-05-sw-engineering-sp24-05/application/backend/
          pm2 reload ecosystem.config.json --update-env
        EOF